In [1]:
import numpy as np
x=np.full([3,4],10)
print(x)


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [2]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
import numpy as np
arr=np.array([0,50])
for x in arr:
    print(0,50)

0 50
0 50


In [5]:
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [16]:
import numpy as np

arr=np.arange(10,51)


if np.all(arr%2==0):
    
    print(arr)
else:
    print("love")


love


In [27]:
import numpy as np
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])